"""second

Revision ID: 035319071278
Revises: 2880a23a2048
Create Date: 2022-11-21 12:27:57.157280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '035319071278'
down_revision = '2880a23a2048'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'board', ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'board', type_='unique')
    # ### end Alembic commands ###
